# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request
on: pull_request

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  ###################################################
  # BUILD
  ###################################################

  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
          - kind: windows
            os: windows-latest
          - kind: macOS
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3

      - name: Build
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake

      - name: Upload Verify Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: verify-test-results
          path: |
            **/*.received.*